fix: update generated proto files (#315)
Set the right dir to generate the histogram package.
Updated outdated generated proto files.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -57,7 +57,17 @@ jobs:
       - name: Install wasm-pack
         run: cargo install wasm-pack
       - name: Run wasm-pack build
-        run: wasm-pack build histogram
+        run: wasm-pack build histogram --out-dir ../gen/histogram
+      - name: Check for changes in generated files
+        shell: bash
+        run: |
+          if git diff --exit-code -- . ":(exclude)gen/histogram/.gitignore" ":(exclude)gen/histogram/histogram_bg.wasm"; then
+            echo "No changes detected in generated files."
+          else
+            echo "Error: Generated files have changed unexpectedly."
+            git diff -- . ":(exclude)gen/histogram/.gitignore" ":(exclude)gen/histogram/histogram_bg.wasm"
+            exit 1
+          fi
       - name: Build
         run: pnpm run build
       - name: Test
